<?php
/**
 * @package     Arastta eCommerce
 * @copyright   2015-2017 Arastta Association. All rights reserved.
 * @copyright   See CREDITS.txt for credits and other copyright notices.
 * @license     GNU GPL version 3; see LICENSE.txt
 * @link        https://arastta.org
 */

// Heading
$_['heading_title'] = 'Các danh mục';

// Text
$_['text_success']          = 'Thành công: Bạn đã sửa các danh mục!';
$_['text_list']             = 'Danh sách danh mục';
$_['text_add']              = 'Thêm danh mục';
$_['text_edit']             = 'Sửa danh mục';
$_['text_default']          = 'Default';
$_['text_preview']          = 'View Category';
$_['text_new_category_seo'] = 'Add a title and description to see how this category might appear in a search engine listing.';

// Column
$_['column_name']       = 'Name';
$_['column_status']     = 'Status';
$_['column_sort_order'] = 'Sắp xếp';
$_['column_action']     = 'Thao tác';

// Entry
$_['entry_name']             = 'Name';
$_['entry_description']      = 'Mô tả';
$_['entry_meta_title']       = 'Tiêu đề thẻ meta';
$_['entry_meta_keyword']     = 'Từ khóa thẻ meta';
$_['entry_meta_description'] = 'Mô tả thẻ meta';
$_['entry_seo_url']          = 'SEO URL';
$_['entry_parent']           = 'Tên cấp cha';
$_['entry_store']            = 'Stores';
$_['entry_image']            = 'Ảnh';
$_['entry_top']              = 'Trên cùng';
$_['entry_sort_order']       = 'Sắp xếp';
$_['entry_status']           = 'Status';
$_['entry_layout']           = 'Layout ghi đè';
$_['entry_update_menu_name'] = 'Update Menu Name';

// Help
$_['help_seo_url']           = 'Do not enter site name or parent category, just the product URL. Leave empty if you want to be generated by the system automatically based on category name.';
$_['help_top']               = 'Hiển thị trong thanh thực đơn trên cùng. Chỉ áp dụng cho các danh mục cấp cha cao nhất.';
$_['help_update_menu_name']  = 'If you checked this field update Menu Category name.';

// Error 
$_['error_warning']    = 'Warning: Please check the form for errors';
$_['error_permission'] = 'Warning: You do not have permission to modify blog categories';
$_['error_name']       = 'Category Name must be between 2 and 32 characters';
$_['error_seo_url']    = 'SEO URL already in use!';
