<?php
/**
 * @package     Arastta eCommerce
 * @copyright   2015-2017 Arastta Association. All rights reserved.
 * @copyright   See CREDITS.txt for credits and other copyright notices.
 * @license     GNU GPL version 3; see LICENSE.txt
 * @link        https://arastta.org
 */

// Heading
$_['heading_title']          = 'Thông tin';
$_['column_status']          = 'Status';

// Text
$_['text_success']           = 'Thành công: Bạn đã thay đổi Thông tin thành công!';
$_['text_list']              = 'Danh sách Thông tin';
$_['text_add']               = 'Thêm Thông tin';
$_['text_edit']              = 'Sửa Thông tin';
$_['text_default']           = 'Mặc định';
$_['text_preview']           = 'View Information';

$_['text_new_information_seo']  = 'Add a title and description to see how this information might appear in a search engine listing.';

// Column
$_['column_title']           = 'Tiêu đề Thông tin';
$_['column_sort_order']      = 'Thứ tự sắp xếp';
$_['column_action']          = 'Thao tác';

// Entry
$_['entry_title']            = 'Tiêu đề Thông tin';
$_['entry_description']      = 'Miêu tả';
$_['entry_store']            = 'Cửa hàng';
$_['entry_meta_title']       = 'Tiêu đề Thẻ Meta';
$_['entry_meta_keyword']     = 'Từ khóa Thẻ Meta';
$_['entry_meta_description'] = 'Miêu tả Thẻ Meta';
$_['entry_seo_url']          = 'SEO URL';
$_['entry_bottom']           = 'Chân trang';
$_['entry_status']           = 'Trạng thái';
$_['entry_sort_order']       = 'Thứ tự sắp xếp';
$_['entry_layout']           = 'Ghi đè Layout';

// Help
$_['help_seo_url']           = 'Do not enter site name, just the information URL. Leave empty if you want to be generated by the system automatically based on information name.';
$_['help_bottom']            = 'Hiển thị dưới chân trang.';

// Error
$_['error_warning']          = 'Cảnh báo: Vui lòng kiểm tra lại biểu mẫu!';
$_['error_permission']       = 'Cảnh báo: Bạn không có quyền thay đổi Thông tin!';
$_['error_title']            = 'Tiêu đề Thông tin từ 3 đến 64 ký tự!';
$_['error_description']      = 'Miêu tả nhiều hơn 3 ký tự!';
$_['error_meta_title']       = 'Tiêu đề Meta có từ 3 đến 255 ký tự!';
$_['error_seo_url']          = 'SEO URL already in use!';
$_['error_account']          = 'Cảnh báo: Không thể xóa trang Thông tin vì trang Thông tin này đã được gắn tới trang Điều khoản của cửa hàng!';
$_['error_checkout']         = 'Cảnh báo: Không thể xóa trang Thông tin vì trang Thông tin này đã được gắn tới trang Điều khoản thanh toán của cửa hàng!';
$_['error_affiliate']        = 'Cảnh báo: Không thể xóa trang Thông tin vì trang Thông tin này đã được gắn tới trang Điều khoản đại lý của cửa hàng!';
$_['error_return']           = 'Cảnh báo: Không thể xóa trang Thông tin vì trang Thông tin này đã được gắn tới trang Điều khoản hoàn trả của cửa hàng!';
$_['error_store']            = 'Warning: This information page cannot be deleted as it is currently used by %s stores!';
