<?php
/**
 * @package     Arastta eCommerce
 * @copyright   2015-2017 Arastta Association. All rights reserved.
 * @copyright   See CREDITS.txt for credits and other copyright notices.
 * @license     GNU GPL version 3; see LICENSE.txt
 * @link        https://arastta.org
 */

// Heading
$_['heading_title']         = 'Nhà sản xuất';

// Text
$_['text_success']          = 'Thành công : Bạn đã thay đổi thành công Nhà sản xuất!';
$_['text_list']             = 'Danh sách Nhà sản xuất';
$_['text_add']              = 'Thêm Nhà sản xuất';
$_['text_edit']             = 'Sửa Nhà sản xuất';
$_['text_default']          = 'Mặc định';
$_['text_percent']          = 'Tỷ lệ phần trăm';
$_['text_amount']           = 'Số tiền cố định';
$_['text_preview']          = 'View Manufacturer';

$_['text_new_manufacturer_seo']  = 'Add a title and description to see how this manufacturer might appear in a search engine listing.';

// Column
$_['column_name']           = 'Tên Nhà sản xuất';
$_['column_sort_order']     = 'Thứ tự sắp xếp';
$_['column_action']         = 'Thao tác';
$_['column_status']         = 'Status';

// Entry
$_['entry_name']             = 'Tên Nhà sản xuất';
$_['entry_description']      = 'Mô tả';
$_['entry_meta_title']       = 'Tiêu đề thẻ meta';
$_['entry_meta_keyword']     = 'Từ khóa thẻ meta';
$_['entry_meta_description'] = 'Mô tả thẻ meta';
$_['entry_seo_url']          = 'SEO URL';
$_['entry_store']            = 'Stores';
$_['entry_image']            = 'Ảnh';
$_['entry_sort_order']       = 'Thứ tự sắp xếp';
$_['entry_status']           = 'Status';
$_['entry_layout']           = 'Layout ghi đè';
$_['entry_type']             = 'Kiểu';

// Help
$_['help_seo_url']           = 'Do not enter site name, just the manufacturer URL. Leave empty if you want to be generated by the system automatically based on manufacturer name.';

// Error
$_['error_permission']       = 'Cảnh báo: Bạn không có quyền thay đổi thông tin Nhà sản xuất!';
$_['error_name']             = 'Tên Nhà sản xuất từ 2 đến 64 ký tự!';
$_['error_meta_title']       = 'Tiêu đề Meta  phải lớn hơn 3 và ít hơn 255 ký tự!';
$_['error_seo_url']          = 'SEO URL already in use!';
$_['error_product']          = 'Cảnh báo: Không thể xóa Nhà sản xuất này vì đã có %s sản phẩm liên quan tới Nhà sản xuất này!';
